"""
Full E2E test setup for vehicle 11 (100TN 6000).

1. Ensures vehicle 11 is properly configured with a dongle
2. Seeds initial telemetry/DTC to bootstrap the UI
3. Prints verification checklist
"""

from __future__ import annotations

import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

from app.db.session import SessionLocal
from app.models.vehicle import Vehicle
from scripts.seed_alert_test_data import _mongo_client_with_fallback


def setup_vehicle_11() -> None:
    """Ensure vehicle 11 has a dongle and seed minimal DTC/telemetry for UI bootstrap."""
    db = SessionLocal()
    try:
        vehicle = db.query(Vehicle).filter(Vehicle.id == 11).first()
        if not vehicle:
            print("❌ Vehicle 11 NOT found in database. Cannot proceed.")
            return

        print(f"\n✅ Vehicle 11 found: {vehicle.license_plate}")
        print(f"   Make/Model: {vehicle.make} {vehicle.model} {vehicle.year}")
        print(f"   Current dongle_id: {vehicle.dongle_id}")
        print(f"   Current status: {vehicle.status}")

        # Ensure dongle is set
        if not vehicle.dongle_id:
            vehicle.dongle_id = f"sim-dongle-11-e2e-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}"
            db.commit()
            print(f"   ✅ Assigned dongle: {vehicle.dongle_id}")
        else:
            print(f"   ✅ Dongle already set: {vehicle.dongle_id}")

    finally:
        db.close()

    # Bootstrap Mongo with seed DTC for Diagnostic page
    client, db_name = _mongo_client_with_fallback()
    try:
        mongo_db = client[db_name]

        # Check existing DTC
        dtc_count = mongo_db.dtc_events.count_documents({"vehicle_id": 11})
        print(f"\n📊 Current DTC events for vehicle 11: {dtc_count}")

        if dtc_count == 0:
            print("   ⚠️  No DTC seeded yet. Will be created by live simulator.")
        else:
            recent_dtc = mongo_db.dtc_events.find_one(
                {"vehicle_id": 11},
                sort=[("last_occurrence", -1)],
            )
            if recent_dtc:
                print(f"   Latest DTC: {recent_dtc.get('code')} - {recent_dtc.get('description')}")

        # Check telemetry bootstrap
        tel_count = mongo_db.telemetry_data.count_documents({"vehicle_id": 11})
        print(f"\n📊 Current telemetry points for vehicle 11: {tel_count}")

    finally:
        client.close()


async def _main() -> None:
    setup_vehicle_11()

    print("\n" + "=" * 60)
    print("✅ SETUP COMPLETE - E2E Test Ready")
    print("=" * 60)
    print("""
Next step: Start the live stream
  python scripts/run_vehicle11_2min_stream.py

Then open browser and verify each page:
  1. Dashboard @ http://127.0.0.1:5173/dashboard
     → Should list vehicle 11 with recent alerts/DTC

  2. Télémétrie @ http://127.0.0.1:5173/telemetry
     → Select vehicle 11 (100TN 6000)
     → Should show live metrics updating every 2 minutes
     → Charts: speed, rpm, fuel_level, engine_temp, battery_voltage

  3. Diagnostic (DTC) @ http://127.0.0.1:5173/dtc
     → Select vehicle 11
     → Should show seeded/generated DTC codes
     → AI Diagnostic should calculate predicted severity

  4. Alertes @ http://127.0.0.1:5173/alerts
     → Should display auto-generated alerts in real time
     → Filter by severity (critical/warning)
     → Status: pending → acknowledged

  5. Historique @ http://127.0.0.1:5173/vehicles
     → Select vehicle 11
     → Alerts history for that vehicle

Expected DTC codes generated by simulator:
  P0562 (Battery low) → CRITICAL
  P0217 (Overheat) → CRITICAL
  P0300 (Misfire) → CRITICAL
  P0171 (Lean) → WARNING
  P0087 (Fuel pressure low) → WARNING

Typical timeline:
  T+0s:    Setup complete
  T+120s:  1st telemetry batch (3 points), DTC inserted, alerts created
  T+240s:  2nd telemetry batch, new DTC cycle
  ... continues indefinitely until Ctrl+C
""")


if __name__ == "__main__":
    import asyncio

    asyncio.run(_main())
